#!/usr/bin/env php
<?php
if (version_compare(PHP_VERSION, '8.1', '<')) {
    exit('Your PHP version must be 8.1 or higher. Current: ' . PHP_VERSION);
}
define('FCPATH', __DIR__ . DIRECTORY_SEPARATOR . 'public' . DIRECTORY_SEPARATOR);
chdir(__DIR__);
$pathsConfig = 'app/Config/Paths.php';
require realpath($pathsConfig) ?: $pathsConfig;
$paths = new Config\Paths();
require $paths->systemDirectory . '/Boot.php';
CodeIgniter\Boot::bootSpark($paths);
